import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import type { Member } from "@/lib/site-data";
import { InquiryModal } from "@/components/inquiry-form";

export function SectionHeading({eyebrow,title,body,action}:{eyebrow:string;title:string;body?:string;action?:{label:string;href:string}}){return <div className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">{eyebrow}</p><h2 className="headline max-w-4xl">{title}</h2>{body&&<p className="lede mt-5">{body}</p>}</div>{action&&<Link className="button secondary shrink-0" href={action.href}>{action.label}<ArrowUpRight size={15}/></Link>}</div>}

export function PageHero({eyebrow,title,body,image}:{eyebrow:string;title:string;body:string;image?:string}){return <section className="relative overflow-hidden border-b border-[#272727] grid-bg"><div className="absolute -right-32 top-0 h-96 w-96 rounded-full bg-[#fd7803]/10 blur-[100px]"/><div className="shell grid min-h-[520px] items-center gap-12 py-20 lg:grid-cols-[1.05fr_.95fr]"> <div className="relative z-10 reveal"><p className="eyebrow">{eyebrow}</p><h1 className="display">{title}</h1><p className="lede mt-7">{body}</p></div>{image&&<div className="relative h-[340px] overflow-hidden border border-[#333] lg:h-[430px]"><Image src={image} alt="" fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover" priority/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent"/><span className="absolute bottom-5 left-5 font-mono text-[.65rem] uppercase tracking-[.14em] text-white/70">210 // UT San Antonio</span></div>}</div></section>}

export function MemberCard({member}:{member:Member}){return <article className="group card overflow-hidden transition hover:-translate-y-1 hover:border-[#fd7803]/60"><div className="relative aspect-[4/5] overflow-hidden bg-[#181818]"><Image src={member.image} alt={member.name} fill sizes="(max-width:700px) 100vw, 33vw" className="object-cover grayscale-[25%] transition duration-500 group-hover:scale-[1.04] group-hover:grayscale-0"/><div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-black to-transparent"/></div><div className="p-5"><h3 className="text-xl font-bold tracking-tight">{member.name}</h3><p className="mt-2 text-sm font-semibold text-[#fd7803]">{member.role}</p><p className="mt-4 text-sm leading-6 text-[#999]">{member.bio}</p></div></article>}

export function CTA(){return <section className="border-y border-[#302313] bg-[#fd7803] text-black"><div className="shell flex flex-col items-start justify-between gap-8 py-14 md:flex-row md:items-center"><div><p className="font-mono text-xs font-bold uppercase tracking-[.15em]">Your next build starts here</p><h2 className="mt-3 text-4xl font-bold tracking-[-.05em] md:text-6xl">Bring your curiosity.</h2></div><InquiryModal kind="join" label="Join 210 Robotics" className="button !border-black !bg-black !text-white"/></div></section>}
